services:

  db-postgres:
    image: postgres:16-alpine
    container_name: db_bank_card
    environment:
      POSTGRES_DB: db_bank_card
      POSTGRES_USER: db_bank_card
      POSTGRES_PASSWORD: db_bank_card
    ports:
      - "5435:5432"
